---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  AuthService
      name:  authentication
      auth_service: "auth-svc:3000"  
spec:
  type: ClusterIP
  selector:
    app: auth-svc
  ports:
  - port: 3000
    name: http-auth-svc
    targetPort: http-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth-svc
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: auth-svc
    spec:
      containers:
      - name: auth-svc
        image: auth_svc:v1
        ports:
        - name: http-api
          containerPort: 3000