---
apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  hello-svc_mapping
      prefix: /hello/
      service: hello-svc
spec:
  selector:
    app: hello-svc
  ports:
  - port: 80
    name: http-hello-svc
    targetPort: http-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-svc
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-svc
    spec:
      containers:
      - name: hello-svc
        image: hello_svc:v1
        ports:
        - name: http-api
          containerPort: 8080